### DISCUSSION TITLE
Possible rename of the response property `phoneNumChanged`

### DISCUSSION THREAD

**Discussion by maxl2287** [camaraproject/NumberRecycling#26] [General]
**Problem description**
After getting in touch with this API for the first time, I was slightly confused about the naming of the property `phoneNumChanged` in the response.
The current property name `phoneNumChanged` in the API response may cause confusion because it implies that the phone number itself has changed, which is not accurate. 
The intent of this property is to indicate whether the subscriber associated with the phone number has changed.

**Possible evolution**
Rename the property to something more descriptive and aligned with its actual purpose and to have a better alignment between the property name and its actual functionality.
Suggested alternatives may be:

- `subscriberChanged`
- `isSubscriberChanged`
- `phoneNumberRecycled`
- `isNumberRecycled`
- etc.

**Additional context**
```yaml
        phoneNumChanged:
          type: boolean
          description: |
            Set to true (Boolean, not string) when there has been a change in the subscriber associated with the specific phone number after “specifiedDate”.

```
